name: Robot_Teneo_Permanent
on:
  schedule:
    - cron: '*/15 * * * *' # S'exécute TOUTES LES 15 MINUTES
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion Furtive Teneo
        run: |
          curl -s -X POST "https://api.teneo.pro" \
          -H "Authorization: Bearer ${{ secrets.TENEO_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"type":"ping"}'
          echo "Points Teneo envoyés avec succès sur GitHub !"
